eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://authenticationservice:9999/uaa/oauth/token_key

redis:
  server: redis
  port: 6379

logging:
  level:
    com.netflix: WARN
    org.springframework: WARN
    com.longmaple: DEBUG


    
