eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true

redis:
  server: redis
  port: 6379

logging:
  level:
    com.netflix: WARN
    org.springframework: WARN
    com.longmaple: DEBUG

security:
  oauth2:
    resource:
      userInfoUri: http://frontend:8080/user
