apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: authenticationservice
  name: authenticationservice
spec:
  ports:
  - name: "9999"
    port: 9999
    targetPort: 9999
    nodePort: 30099
  type: NodePort
  selector:
    io.kompose.service: authenticationservice
status:
  loadBalancer: {}
