server:
  port: 5555

logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.longmaple: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8901/oauth/token
      user-authorization-uri: http://localhost:8901/oauth/authorize
      client-id: webapp
      client-secret: abcd1234
      scope: user:profile:read user:profile:write
      pre-established-redirect-uri: http://localhost:5007/callback
      use-current-uri: false
      client-authentication-scheme: header
    resource:
      jwt:
        key-uri: http://localhost:8901/oauth/token_key