apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: configserver
  name: configserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: configserver
    spec:
      containers:
      - env:
        - name: ENCRYPT_KEY
          value: IMSYMMETRIC
        - name: EUREKASERVER_PORT
          value: "8761"
        - name: EUREKASERVER_URI
          value: http://eurekaserver:8761/eureka/
        image: huajwang/confsvr:ttmall
        name: configserver
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
status: {}
